# port details
server:
 port: 9096		
#Application Name
spring:
   application:
     name: JRTP-CorrespondenceService

# mail properties
   mail:
    host: smtp.gmail.com
    port: 587
    username: gugulothsagarnaik01@gmail.com
    password: naikGMAIL@456
    properties:
      mail:
        transport:
         protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
             enable: true
             required: true	 
  