# port details
server:
 port: 9096		
#Application Name
spring:
   application:
     name: JRTP-CorrespondenceService
#config server
   config:
    import: optional:configserver:http://localhost:8888
# Admin Server properties
   boot:
     Admin:
       client:
         url: http://localhost:9999
# eureka server properties
eureka:
 client:
  service-url:
   default-zone: http://localhost:8761/eureka

# mail properties
   mail:
    host: smtp.gmail.com
    port: 587
    username: gugulothsagarnaik01@gmail.com
    password: naikGMAIL@456
    properties:
      mail:
        transport:
         protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
             enable: true
             required: true	 
#actuators properties
management:
  endpoint:
   env:
    enabled: true
    show-values: always
   health:
    show-details: always
  endpoints:
    web:
     exposure:
       include: '*'  