server:
 port: 9094
spring:
  application:
    name: JRTP-EligibilityDeterminationService
#config server props
  config:
   import: optional:configserver:http://localhost:8888

# Admin Server properties
  boot:
    Admin:
     client:
      url: http://localhost:9999
# eureka server properties
eureka:
  client:
   service-url:
     default-zone: http://localhost:8761/eureka
#Actuator Details
management:
   endpoint:
     env:
      enabled: true
      show-values: always
     health:
      show-details: always
   endpoints:
     web:
      exposure:
        include: '*'